name: Publish release
on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    name: Run tests and publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: earthly +test
      - run: earthly +testacc
      - run: earthly +release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          draft: false
          prerelease: true
          files: |
            ./bin/*.zip
            ./bin/vault-acme_SHA256SUMS
